#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# SlackBuild recipe. Submit via https://slackbuilds.org/
PRGNAM=graft
VERSION=${VERSION:-0.2.2}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e
rm -rf "$PKG"
mkdir -p "$TMP" "$PKG" "$OUTPUT"
cd "$TMP"
rm -rf "$PRGNAM-$VERSION"
tar xvf "$CWD/$PRGNAM-$VERSION.tar.gz"
cd "$PRGNAM-$VERSION"
chown -R root:root .
cargo build --release --locked --bin graft
install -D -m 0755 target/release/graft "$PKG/usr/bin/graft"
mkdir -p "$PKG/usr/doc/$PRGNAM-$VERSION"
cp -a README.md LICENSE "$PKG/usr/doc/$PRGNAM-$VERSION"
cd "$PKG"
/sbin/makepkg -l y -c n "$OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}"
