--- Makefile.orig	2025-08-12 19:37:48.000000000 +1000
+++ Makefile	2026-07-17 10:19:14.350141808 +1000
@@ -3,8 +3,10 @@
 # By Nils M Holm, 2007-2025
 # In the public domain
 
+DESTDIR=
+
 # Change at least this line:
-PREFIX= /u
+PREFIX= /usr
 
 # Base version and Release
 BASE=		20250805
@@ -56,7 +58,7 @@
 S9DIR=	$(PREFIX)/share/s9fes
 BINDIR=	$(PREFIX)/bin
 INCDIR=	$(PREFIX)/include
-LIBDIR=	$(PREFIX)/lib
+LIBDIR=	$(PREFIX)/lib$(LIBDIRSUFFIX)
 MANDIR=	$(PREFIX)/man/man1
 
 # Set up environment to be used during the build process
@@ -129,82 +131,83 @@
 # old version of install(1) may need -c
 #C=-c
 install-s9:	s9 s9.scm s9.image s9.1.gz libs9core.a
-	install -d -m 0755 $(S9DIR)
-	install -d -m 0755 $(S9DIR)/help
-	install -d -m 0755 $(S9DIR)/help/sys-unix
-	install -d -m 0755 $(S9DIR)/help/curses
-	install -d -m 0755 $(S9DIR)/help/csv
-	install -d -m 0755 $(BINDIR)
-	install -d -m 0755 $(LIBDIR)
-	install -d -m 0755 $(INCDIR)
-	install -d -m 0755 $(MANDIR)
-	install $C -m 0755 s9 $(BINDIR)
-	strip $(BINDIR)/s9
-	install $C -m 0644 s9.scm $(S9DIR)
-	install $C -m 0644 s9.image $(S9DIR)
-	install $C -m 0644 lib/* $(S9DIR)
-	install $C -m 0644 ext/sys-unix/*.scm $(S9DIR)
-	install $C -m 0644 ext/curses/*.scm $(S9DIR)
-	install $C -m 0644 ext/csv/*.scm $(S9DIR)
-	install $C -m 0644 contrib/* $(S9DIR)
-	install $C -m 0644 s9.1.gz $(MANDIR)
-	(tar cf - help | tar xfC - $(S9DIR))
-	install $C -m 0644 libs9core.a $(LIBDIR)
-	install $C -m 0644 s9core.h $(INCDIR)
-	install $C -m 0644 s9import.h $(INCDIR)
+	install -d -m 0755 $(DESTDIR)$(S9DIR)
+	install -d -m 0755 $(DESTDIR)$(S9DIR)/help
+	install -d -m 0755 $(DESTDIR)$(S9DIR)/help/sys-unix
+	install -d -m 0755 $(DESTDIR)$(S9DIR)/help/curses
+	install -d -m 0755 $(DESTDIR)$(S9DIR)/help/csv
+	install -d -m 0755 $(DESTDIR)$(BINDIR)
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)
+	install -d -m 0755 $(DESTDIR)$(INCDIR)
+	install -d -m 0755 $(DESTDIR)$(MANDIR)
+	install $C -m 0755 s9 $(DESTDIR)$(BINDIR)
+	strip $(DESTDIR)$(BINDIR)/s9
+	install $C -m 0644 s9.scm $(DESTDIR)$(S9DIR)
+	install $C -m 0644 s9.image $(DESTDIR)$(S9DIR)
+	install $C -m 0644 lib/* $(DESTDIR)$(S9DIR)
+	install $C -m 0644 ext/sys-unix/*.scm $(DESTDIR)$(S9DIR)
+	install $C -m 0644 ext/curses/*.scm $(DESTDIR)$(S9DIR)
+	install $C -m 0644 ext/csv/*.scm $(DESTDIR)$(S9DIR)
+	install $C -m 0644 contrib/* $(DESTDIR)$(S9DIR)
+	install $C -m 0644 s9.1.gz $(DESTDIR)$(MANDIR)
+	(tar cf - help | tar xfC - $(DESTDIR)$(S9DIR))
+	install $C -m 0644 libs9core.a $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9core.h $(DESTDIR)$(INCDIR)
+	install $C -m 0644 s9import.h $(DESTDIR)$(INCDIR)
 
 install-util:
-	$(SETPREFIX) <prog/s9help.scm >$(BINDIR)/s9help
-	$(SETPREFIX) <prog/s9resolve.scm >$(BINDIR)/s9resolve
-	$(SETPREFIX) <prog/scm2html1.scm >$(BINDIR)/scm2html
-	$(SETPREFIX) <prog/scmpp.scm >$(BINDIR)/scmpp
-	-chmod +x $(BINDIR)/s9help	\
-		  $(BINDIR)/s9resolve	\
-		  $(BINDIR)/scm2html	\
-		  $(BINDIR)/scmpp
+	mkdir -p $(DESTDIR)$(BINDIR)
+	$(SETPREFIX) <prog/s9help.scm >$(DESTDIR)$(BINDIR)/s9help
+	$(SETPREFIX) <prog/s9resolve.scm >$(DESTDIR)$(BINDIR)/s9resolve
+	$(SETPREFIX) <prog/scm2html1.scm >$(DESTDIR)$(BINDIR)/scm2html
+	$(SETPREFIX) <prog/scmpp.scm >$(DESTDIR)$(BINDIR)/scmpp
+	-chmod +x $(DESTDIR)$(BINDIR)/s9help	\
+		  $(DESTDIR)$(BINDIR)/s9resolve	\
+		  $(DESTDIR)$(BINDIR)/scm2html	\
+		  $(DESTDIR)$(BINDIR)/scmpp
 
 install-progs:
-	$(SETPREFIX) <prog/advgen.scm >$(BINDIR)/advgen
-	$(SETPREFIX) <prog/c2html1.scm >$(BINDIR)/c2html
-	$(SETPREFIX) <prog/cols.scm >$(BINDIR)/cols
-	$(SETPREFIX) <prog/dupes.scm >$(BINDIR)/dupes
-	$(SETPREFIX) <prog/edoc.scm.edoc >$(BINDIR)/edoc
-	$(SETPREFIX) <prog/htmlify.scm >$(BINDIR)/htmlify
-	$(SETPREFIX) <prog/s9hts.scm >$(BINDIR)/s9hts
-	$(SETPREFIX) <prog/soccat.scm >$(BINDIR)/soccat
-	-chmod +x $(BINDIR)/advgen	\
-		  $(BINDIR)/c2html	\
-		  $(BINDIR)/cols	\
-		  $(BINDIR)/dupes	\
-		  $(BINDIR)/edoc	\
-		  $(BINDIR)/htmlify	\
-		  $(BINDIR)/s9hts	\
-		  $(BINDIR)/soccat
+	$(SETPREFIX) <prog/advgen.scm >$(DESTDIR)$(BINDIR)/advgen
+	$(SETPREFIX) <prog/c2html1.scm >$(DESTDIR)$(BINDIR)/c2html
+	$(SETPREFIX) <prog/cols.scm >$(DESTDIR)$(BINDIR)/cols
+	$(SETPREFIX) <prog/dupes.scm >$(DESTDIR)$(BINDIR)/dupes
+	$(SETPREFIX) <prog/edoc.scm.edoc >$(DESTDIR)$(BINDIR)/edoc
+	$(SETPREFIX) <prog/htmlify.scm >$(DESTDIR)$(BINDIR)/htmlify
+	$(SETPREFIX) <prog/s9hts.scm >$(DESTDIR)$(BINDIR)/s9hts
+	$(SETPREFIX) <prog/soccat.scm >$(DESTDIR)$(BINDIR)/soccat
+	-chmod +x $(DESTDIR)$(BINDIR)/advgen	\
+		  $(DESTDIR)$(BINDIR)/c2html	\
+		  $(DESTDIR)$(BINDIR)/cols	\
+		  $(DESTDIR)$(BINDIR)/dupes	\
+		  $(DESTDIR)$(BINDIR)/edoc	\
+		  $(DESTDIR)$(BINDIR)/htmlify	\
+		  $(DESTDIR)$(BINDIR)/s9hts	\
+		  $(DESTDIR)$(BINDIR)/soccat
 
 deinstall:	deinstall-s9 deinstall-util deinstall-progs
 
 deinstall-s9:
 	rm -f $(S9DIR)/help/* && rmdir $(S9DIR)/help
 	rm -f $(S9DIR)/* && rmdir $(S9DIR)
-	rm -f $(BINDIR)/s9
-	-rmdir $(BINDIR)
-	-rmdir $(MANDIR)
+	rm -f $(DESTDIR)$(BINDIR)/s9
+	-rmdir $(DESTDIR)$(BINDIR)
+	-rmdir $(DESTDIR)$(MANDIR)
 
 deinstall-util:
-	rm -f $(BINDIR)/s9help		\
-	      $(BINDIR)/s9resolve	\
-	      $(BINDIR)/scm2html	\
-	      $(BINDIR)/scmpp
+	rm -f $(DESTDIR)$(BINDIR)/s9help		\
+	      $(DESTDIR)$(BINDIR)/s9resolve	\
+	      $(DESTDIR)$(BINDIR)/scm2html	\
+	      $(DESTDIR)$(BINDIR)/scmpp
 
 deinstall-progs:
-	rm -f $(BINDIR)/advgen		\
-	      $(BINDIR)/c2html		\
-	      $(BINDIR)/cols		\
-	      $(BINDIR)/dupes		\
-	      $(BINDIR)/edoc		\
-	      $(BINDIR)/htmlify		\
-	      $(BINDIR)/s9hts		\
-	      $(BINDIR)/soccat
+	rm -f $(DESTDIR)$(BINDIR)/advgen		\
+	      $(DESTDIR)$(BINDIR)/c2html		\
+	      $(DESTDIR)$(BINDIR)/cols		\
+	      $(DESTDIR)$(BINDIR)/dupes		\
+	      $(DESTDIR)$(BINDIR)/edoc		\
+	      $(DESTDIR)$(BINDIR)/htmlify		\
+	      $(DESTDIR)$(BINDIR)/s9hts		\
+	      $(DESTDIR)$(BINDIR)/soccat
 
 tabs:
 	@find . -name \*.scm -exec grep -l "	" {} \;
