#!/bin/bash

# Slackware build script for <appname>

# Copyright 2023  Martin Rodriguez, Guadalajara Mexico
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=thorium-browser
VERSION=${VERSION:-122.0.6261.132}
BUILD=${BUILD:-1}
TAG=${TAG:-_SBo}
PKGTYPE=${PKGTYPE:-tgz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
      i?86) ARCH=i586 ;;
    x86_64) DEBARCH="amd64" ; ARCH=x86_64 ;;
      arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
# the name of the created package would be, and then exit. This information
# could be useful to other scripts.
if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-${VERSION}-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

if ! /bin/ls ${PRGNAM}*$DEBARCH*.deb 1> /dev/null 2> /dev/null ; then
  cat << EOF

This is a script to repackage a Debian/Ubuntu Thorium .deb package
for Slackware.  Run this script in the same directory as one of these
binary packages:

  ${PRGNAM}_${VERSION}_$DEBARCH.deb  (for 64-bit x86_64 with avx support)

This will create a Slackware .$PKGTYPE package.  Install it with
installpkg or use upgradepkg to upgrade from a previous version.

EOF
  exit 1
fi

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

cd $PKG
ar p $CWD/${PRGNAM}_${VERSION}_$DEBARCH.deb data.tar.xz | tar xJv || exit 1
cd ..

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

# Make sure top-level perms are correct:
chmod 0755 .

# This needs to be setuid root:
chmod 4711 $PKG/opt/chromium.org/thorium/chrome-sandbox

# The cron job is for Debian/Ubuntu only:
rm -rf $PKG/etc

# Strip binaries and libraries
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mv $PKG/usr/share/man $PKG/usr/man

# Install a .desktop launcher:
sed -i -e "s#Icon=thorium-browser#Icon=/opt/chromium.org/thorium/product_logo_256.png#" \
  $PKG/usr/share/applications/thorium-browser.desktop

mkdir -p $PKG/usr/doc/$PRGNAM-${VERSION}
mv $PKG/usr/share/doc/$PRGNAM/* $PKG/usr/doc/$PRGNAM-${VERSION}
rm -rf $PKG/usr/share/doc
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-${VERSION}/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# Make the package
cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-${VERSION}-$ARCH-$BUILD$TAG.$PKGTYPE
