perl-Try-Tiny
perl-Test-Harness
perl-Test-Fatal
perl-Meta-Requirements-Range
perl-ExtUtils-Config
perl-B-COW
perl-lwp-mediatypes
perl-http-date
perl-encode-locale
perl-Test-NoWarnings
perl-Test-Needs
perl-JSON
perl-IO-HTML
perl-ExtUtils-InstallPaths
perl-ExtUtils-Helpers
perl-Clone
perl-CPAN-Requirements-Dynamic
perl-http-message
perl-html-tagset
perl-Test-Requires
perl-Test-Deep
perl-Module-Build-Tiny
rust-opt
perl-www-robotrules
perl-net-http
perl-http-negotiate
perl-http-daemon
perl-http-cookies
perl-html-parser
perl-file-listing
perl-extutils-pkgconfig
perl-extutils-depends
perl-Test-Warnings
perl-Test-RequiresInternet
perl-HTTP-CookieJar
perl-glib
perl-file-slurper
perl-cairo
perl-Mozilla-CA
libwww-perl
deno
yt-dlp-bin
perl-io-uncompress-brotli
perl-data-dump
perl-Term-ReadLine-Gnu
perl-Module-Build
perl-LWP-Protocol-https
perl-Glib-Object-Introspection
perl-File-ShareDir-Install
perl-Class-Inspector
perl-Cairo-GObject
pipe-viewer
perl-Gtk3
perl-File-ShareDir
